cascade:
  _merge: deep
cascade:
- _target:
    path: /audits/**/*
    type: audits
  outputs:
    - html
    - json
    - declaration
    - declarationpage
    - declarationeco
    - declarationecopage
- _target:
    path: /audits/**/**
    type: audits
  outputs:
    - html
    - json
    - declaration
    - declarationpage
    - declarationeco
    - declarationecopage
    - accessibility
    - raweb
    - raam
    - ecoconception
    - opquast
    - publishing
    - recommendation
    - performance
    - accessibilitypage
    - rawebpage
    - raampage
    - ecoindexpage
    - ecoconceptionpage
    - opquastpage
    - publishingpage
    - recommendationpage
    - performancepage