cascade:
  - target:
      path: /audits/**/*
      type: audits
    outputs:
      - html
      - json
      - declaration
      - declarationeco
  - target:
      path: /audits/**/**
      type: audits
    outputs:
      - html
      - json
      - declaration
      - declarationeco
      - accessibility
      - raweb
      - raam
      - ecoconception
      - opquast
      - publishing
      - recommendation
      - performance
