baseURL = "https://lowdit.github.io/sandbox/"
languageCode = "fr-FR"
title = "Sandbox Frago"

theme = ["frago"]

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
