baseURL = ""
languageCode = "fr-FR"
title = "Sandbox Frago"

theme = ["github.com/lowdit/frago"]

ignoreErrors = ["error-remote-getcsv"]

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
