baseURL = "https://frago-sandbox.netlify.app/"
languageCode = "fr-FR"
title = "Sandbox Frago"

theme = ["github.com/lowdit/frago"]

ignoreLogs = ['error-remote-getcsv']

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
