baseURL = "/"
paginate = "10"

title = "Observatoire Accessibilité"

languageCode = "fr-FR"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false
enableInlineShortcodes = true
removePathAccents = true
enableGitInfo = true

disableKinds = ["RSS", "sitemap", "taxonomy", "taxonomyTerm"]

[outputformats]
  _merge = 'deep'

[outputFormats.declarationpage]
  baseName = "declaration"
  mediaType = "text/html"
  notAlternative = false
  permalinkable = true
  isHTML = true
[outputFormats.declaration]
  baseName = "declaration"
  mediaType = "text/plain"
  isPlainText = true
  notAlternative = false
[outputFormats.declarationeco]
  baseName = "declaration-ecoconception"
  mediaType = "text/plain"
  isPlainText = true
  notAlternative = false
[outputFormats.accessibility]
  baseName = "accessibility"
  mediaType = "application/json"
  isPlainText = true
  notAlternative = false
[outputFormats.raweb]
  baseName = "raweb"
  mediaType = "application/json"
  isPlainText = true
  notAlternative = false
[outputFormats.raam]
  baseName = "raam"
  mediaType = "application/json"
  isPlainText = true
  notAlternative = false
[outputFormats.ecoindex]
  baseName = "ecoindex"
  mediaType = "application/json"
  isPlainText = true
  notAlternative = false
[outputFormats.ecoconception]
  baseName = "ecoconception"
  mediaType = "application/json"
  isPlainText = true
  notAlternative = false
[outputFormats.publishing]
  baseName = "publishing"
  mediaType = "application/json"
  isPlainText = true
  notAlternative = false
[outputFormats.opquast]
  baseName = "opquast"
  mediaType = "application/json"
  isPlainText = true
  notAlternative = false
[outputFormats.cigref]
  baseName = "cigref"
  mediaType = "application/json"
  isPlainText = true
  notAlternative = false
[outputFormats.greenit]
  baseName = "greenit"
  mediaType = "application/json"
  isPlainText = true
  notAlternative = false
[outputFormats.recommendation]
  baseName = "recommendation"
  mediaType = "application/json"
  isPlainText = true
  notAlternative = false
[outputFormats.performance]
  baseName = "performance"
  mediaType = "application/json"
  isPlainText = true
  notAlternative = false
