baseURL = "https://frago-sandbox.netlify.app/"
title = "Sandbox Frago"

theme = ["github.com/lowdit/frago"]

ignoreLogs = ['error-remote-getcsv']

languageCode = "fr-FR"
defaultContentLanguage = "fr"
removePathAccents = true
enableGitInfo = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[params]
  organisation = "Mon organisation dans le fichier principal"
